/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8bca2e67-df18-4f9d-8139-9e3bd2cb5ae0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KHD7vBztY",
    "aws_user_pools_web_client_id": "3umrs4m10hv5akh4gbu6l57slj",
    "oauth": {
        "domain": "wptpui90025c74-90025c74-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://main.d3t0eddq8sk7xv.amplifyapp.com/dashboard/",
        "redirectSignOut": "https://main.d3t0eddq8sk7xv.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
